### PR TITLE
bump min widgets version for jlab2

### PR DESCRIPTION
**Pull request by timkpaine**

### CODE REVIEW

**Comment by sgratzl** [comment]
I just released a new version with lineupjs v4.0 which should be compatible.

**Comment by timkpaine** [comment]
This is still going to break for people when used in conjunction with other libraries unless you support 3 as well. E.g. the official sidecar library will cause your latest release to break https://github.com/jupyter-widgets/jupyterlab-sidecar/blob/master/package.json#L41

I recommend ^2 || ^3 || ^4 for maximum compatibility.

**Comment by sgratzl** [comment]
atm it looks like that:

https://github.com/lineupjs/lineup_widget/blob/c158f1467b5b1251b7a57a4bb5c570421dd2c3e8/js/package.json#L47

which works for me in another project

**Comment by timkpaine** [comment]
It causes my installation to break due to jupyter-widgets/base 3 being the resolved version.

**Comment by sgratzl** [comment]
I tried to follow the same pattern as I used to do in another project: https://github.com/upsetjs/upsetjs_jupyter_widget/#installation. Have you tried to install the manager manually before?

**Comment by timkpaine** [comment]
I have about 40 extensions in my deployment, I have the latest non-alpha jupyterlab manager (2.0.0). I have lineup_widget installed from my fork for now which works fine, and the extension system for JupyterLab is consolidating to hopefully alleviate this problem anyway.

**Pull request closed without merging**
