### PR TITLE
bump widgets version for jlab 1.0, pull version from package.json

### PR DESCRIPTION
**Pull request by timkpaine**
Simple version bump + manage version in 1 spot
Screen Shot 2019-09-06 at 11 19 04 AM

### CODE REVIEW

**Comment by timkpaine** [comment]
unclear if the CI errors are related, the first is missing a node install and the second looks like tsc wasn't run?

**Comment by sgratzl** [comment]
re circleci errors, should be fixed when updating to the latest master. 

re version from package.json: as described in the README there are actually three files in which the version needs to be changed. Since I have to edit it anyhow in both python and JavaScript I was thinking, I avoid including the whole package.json in the bundle by also editing a third file.

**Comment by timkpaine** [comment]
@sgratzl so would you rather i revert it or no? I wouldnt be concerned about the bundle size as the minified package.json is small. its also very easy to have python read the version out of the package.json, as some projects do.

**Comment by sgratzl** [comment]
if you could centralize the version into a single one that would be great. Tho, I'm not sure whether the package.json is available when python package is installed.

**Pull request closed without merging**
